import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faHome,
  faGraduationCap,
  faCheckSquare,
  faCoffee,
  faSlidersH,
  faUniversity,
  faCodeBranch,
  faTimes,
  faSmile,
  faStar,
  faCopy,
  faSearch,
  faCog,
  faQuestionCircle,
  faEnvelope,
  faFilePdf,
  faMicrochip,
  faSatelliteDish,
  faLightbulb,
  faHeart,
  faComments,
  faListAlt,
  faTable,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fab,
  faEnvelope,
  faFilePdf,
  faHome,
  faGraduationCap,
  faCheckSquare,
  faCoffee,
  faSlidersH,
  faMicrochip,
  faSatelliteDish,
  faLightbulb,
  faCodeBranch,
  faHeart,
  faListAlt,
  faTable,
  faComments,
  faUniversity,
  faCodeBranch,
  faTimes,
  faSmile,
  faStar,
  faCopy,
  faSearch,
  faCog,
  faQuestionCircle,
);
